export default {
  MOVE_FEATURES: "MOVE_FEATURES",
  MOVE_TUTORIALS: "MOVE_TUTORIALS",
  INITIALIZE_FEATURES: "INITIALIZE_FEATURES_SUCCESS",
  GET_VEHICLE: "GET_VEHICLE_SUCCESS",
  GET_TUTORIALS: "GET_TUTORIALS_SUCCESS",
  BEGIN_API_CALL: "BEGIN_API_CALL"
};
