export default {
  MOVE_FEATURES: "MOVE_FEATURES",
  MOVE_TUTORIALS: "MOVE_TUTORIALS",
  STEP_TUTORIALS: "STEP_TUTORIALS",
  MOVE_VIDEOS: "MOVE_VIDEOS",
  STEP_VIDEOS: "STEP_VIDEOS",
  INITIALIZE_FEATURES: "INITIALIZE_FEATURES_SUCCESS",
  GET_VEHICLE: "GET_VEHICLE_SUCCESS",
  GET_TUTORIALS: "GET_TUTORIALS_SUCCESS",
  BEGIN_API_CALL: "BEGIN_API_CALL"
};
